### PR TITLE
updating url for rise-google-sheet component in bower.json file

### PR DESCRIPTION
**Pull request by pcsandford**
@mmeiers please review. I changed the url as per Stuart's message. Thanks!

### CODE REVIEW

**Comment by mmeiers** [comment]
:+1:

**Comment by stulees** [comment]
@pcsandford Hold off merging this. It turns out the repo name may not have had to change after all. I'll let you know when I can confirm, thanks.

**Comment by pcsandford** [comment]
@stulees no problem, thanks!

**Comment by stulees** [comment]
@pcsandford Turns out repo name does indeed have to change, so this PR is good to merge. Thanks

**Pull request merged**
